<<<<<<< HEAD
/* VERIFICA SE O ALWAYSON ESTA HABILITADO E EXECUTANDO */  

      DECLARE @ISHADRENABLED AS SQL_VARIANT
      SET @ISHADRENABLED = (SELECT SERVERPROPERTY('ISHADRENABLED'))
      IF ( @ISHADRENABLED =1)
            BEGIN 
            
            SELECT CASE SERVERPROPERTY('HADRMANAGERSTATUS') 
                        WHEN 0 THEN 'ALWAYSON - NOT STARTED, PENDING COMMUNICATION.'
                        WHEN 1 THEN 'ALWAYSON - STARTED AND RUNNING.'
                        WHEN 2 THEN 'ALWAYSON - NOT STARTED AND FAILED.'
                        ELSE 'ALWAYSON - INPUT IS NOT VALID, AN ERROR, OR NOT APPLICABLE.'
                        END
            END

/* MONITORACAO – <> 1 */      

      DECLARE @ISHADRENABLED AS SQL_VARIANT
      SET @ISHADRENABLED = (SELECT SERVERPROPERTY('ISHADRENABLED'))
      IF ( @ISHADRENABLED =1)
            BEGIN 
            SELECT SERVERPROPERTY('HADRMANAGERSTATUS') 
            END

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA SE EXISTE PAGINAS A SEREM RECUPERADAS*/
/*MONITORACAO - > 0 */
      SELECT COUNT(*) AS QTD_PAGES_REPAIR
      FROM SYS.DM_HADR_AUTO_PAGE_REPAIR



/*VERIFICA O STATUS DO GRUPO*/
/*MONITORACAO APENAS PRIMARIO- PRIMARY_RECOVERY_HEALTH_DESC<> ONLINE E  SYNCHRONIZATION_HEALTH_DESC <> HEALTHY*/
      SELECT AG_NAME
                  ,PRIMARY_RECOVERY_HEALTH_DESC
                  ,SYNCHRONIZATION_HEALTH_DESC
      FROM SYS.DM_HADR_AVAILABILITY_GROUP_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA STATUS DAS BASES DE DADOS REPLICADA*/

      SELECT AG_NAME
            ,REPLICA_SERVER_NAME
            ,DB_NAME(DATABASE_ID) AS DBNAME
            ,IS_LOCAL
            ,IS_PRIMARY_REPLICA
            ,SYNCHRONIZATION_STATE_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,DATABASE_STATE_DESC
            ,SUSPEND_REASON_DESC
            ,LAST_RECEIVED_TIME
            ,LAST_COMMIT_TIME
            ,SECONDARY_LAG_SECONDS
      FROM SYS.DM_HADR_DATABASE_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID


/*MONITORACAO - SYNCHRONIZATION_STATE_DESC <> SYNCHRONIZING E SYNCHRONIZED 
SYNCHRONIZATION_HEALTH_DESC <> HEALTHY
SUSPEND_REASON_DESC <> NULL
SECONDARY_LAG_SECONDS <> NULL AND > 0
*/

      SELECT REPLICA_SERVER_NAME
            ,DB_NAME(DATABASE_ID) AS DBNAME
            ,SYNCHRONIZATION_STATE_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,SUSPEND_REASON_DESC
            ,SECONDARY_LAG_SECONDS
      FROM SYS.DM_HADR_DATABASE_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

/************************************************************************************************************/
/************************************************************************************************************/


/*VERIFICA OS SERVIDORES ENVOLVIDOS NA REPLICA*/

      SELECT AG_NAME
            ,REPLICA_SERVER_NAME
            ,ROLE_DESC
            ,OPERATIONAL_STATE_DESC
            ,RECOVERY_HEALTH_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,CONNECTED_STATE_DESC
            ,LAST_CONNECT_ERROR_NUMBER
            ,LAST_CONNECT_ERROR_DESCRIPTION
            ,LAST_CONNECT_ERROR_TIMESTAMP
      FROM SYS.DM_HADR_AVAILABILITY_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

      
      SELECT MEMBER_NAME
                  ,MEMBER_TYPE_DESC
                  ,MEMBER_STATE_DESC
      FROM SYS.DM_HADR_CLUSTER_MEMBERS   

/*MONITORACAO - OPERATIONAL_STATE_DESC <> ONLINE E NULL 
RECOVERY_HEALTH_DESC <> ONLINE E NULL 
SYNCHRONIZATION_HEALTH_DESC <> HEALTHY
CONNECTED_STATE_DESC <> CONNECTED
LAST_CONNECT_ERROR_TIMESTAMP < 5 MIN
*/

      SELECT REPLICA_SERVER_NAME
            ,OPERATIONAL_STATE_DESC
            ,RECOVERY_HEALTH_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,CONNECTED_STATE_DESC
            ,LAST_CONNECT_ERROR_TIMESTAMP
      FROM SYS.DM_HADR_AVAILABILITY_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

/*MONITORACAO - MEMBER_STATE_DESC <> UP*/

      
      SELECT MEMBER_NAME
                  ,MEMBER_TYPE_DESC
                  ,MEMBER_STATE_DESC
      FROM SYS.DM_HADR_CLUSTER_MEMBERS

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA LISTENER STATE*/

      SELECT LISTENER_ID
                  ,IP_ADDRESS
                  ,TYPE_DESC
                  ,STATE_DESC
                  ,START_TIME
      FROM SYS.DM_TCP_LISTENER_STATES

/*MONITORACAO - STATE_DESC <> ONLINE*/

      SELECT LISTENER_ID
                  ,STATE_DESC
      FROM SYS.DM_TCP_LISTENER_STATES
=======
/* VERIFICA SE O ALWAYSON ESTA HABILITADO E EXECUTANDO */  

      DECLARE @ISHADRENABLED AS SQL_VARIANT
      SET @ISHADRENABLED = (SELECT SERVERPROPERTY('ISHADRENABLED'))
      IF ( @ISHADRENABLED =1)
            BEGIN 
            
            SELECT CASE SERVERPROPERTY('HADRMANAGERSTATUS') 
                        WHEN 0 THEN 'ALWAYSON - NOT STARTED, PENDING COMMUNICATION.'
                        WHEN 1 THEN 'ALWAYSON - STARTED AND RUNNING.'
                        WHEN 2 THEN 'ALWAYSON - NOT STARTED AND FAILED.'
                        ELSE 'ALWAYSON - INPUT IS NOT VALID, AN ERROR, OR NOT APPLICABLE.'
                        END
            END

/* MONITORACAO – <> 1 */      

      DECLARE @ISHADRENABLED AS SQL_VARIANT
      SET @ISHADRENABLED = (SELECT SERVERPROPERTY('ISHADRENABLED'))
      IF ( @ISHADRENABLED =1)
            BEGIN 
            SELECT SERVERPROPERTY('HADRMANAGERSTATUS') 
            END

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA SE EXISTE PAGINAS A SEREM RECUPERADAS*/
/*MONITORACAO - > 0 */
      SELECT COUNT(*) AS QTD_PAGES_REPAIR
      FROM SYS.DM_HADR_AUTO_PAGE_REPAIR



/*VERIFICA O STATUS DO GRUPO*/
/*MONITORACAO APENAS PRIMARIO- PRIMARY_RECOVERY_HEALTH_DESC<> ONLINE E  SYNCHRONIZATION_HEALTH_DESC <> HEALTHY*/
      SELECT AG_NAME
                  ,PRIMARY_RECOVERY_HEALTH_DESC
                  ,SYNCHRONIZATION_HEALTH_DESC
      FROM SYS.DM_HADR_AVAILABILITY_GROUP_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA STATUS DAS BASES DE DADOS REPLICADA*/

      SELECT AG_NAME
            ,REPLICA_SERVER_NAME
            ,DB_NAME(DATABASE_ID) AS DBNAME
            ,IS_LOCAL
            ,IS_PRIMARY_REPLICA
            ,SYNCHRONIZATION_STATE_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,DATABASE_STATE_DESC
            ,SUSPEND_REASON_DESC
            ,LAST_RECEIVED_TIME
            ,LAST_COMMIT_TIME
            ,SECONDARY_LAG_SECONDS
      FROM SYS.DM_HADR_DATABASE_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID


/*MONITORACAO - SYNCHRONIZATION_STATE_DESC <> SYNCHRONIZING E SYNCHRONIZED 
SYNCHRONIZATION_HEALTH_DESC <> HEALTHY
SUSPEND_REASON_DESC <> NULL
SECONDARY_LAG_SECONDS <> NULL AND > 0
*/

      SELECT REPLICA_SERVER_NAME
            ,DB_NAME(DATABASE_ID) AS DBNAME
            ,SYNCHRONIZATION_STATE_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,SUSPEND_REASON_DESC
            ,SECONDARY_LAG_SECONDS
      FROM SYS.DM_HADR_DATABASE_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

/************************************************************************************************************/
/************************************************************************************************************/


/*VERIFICA OS SERVIDORES ENVOLVIDOS NA REPLICA*/

      SELECT AG_NAME
            ,REPLICA_SERVER_NAME
            ,ROLE_DESC
            ,OPERATIONAL_STATE_DESC
            ,RECOVERY_HEALTH_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,CONNECTED_STATE_DESC
            ,LAST_CONNECT_ERROR_NUMBER
            ,LAST_CONNECT_ERROR_DESCRIPTION
            ,LAST_CONNECT_ERROR_TIMESTAMP
      FROM SYS.DM_HADR_AVAILABILITY_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

      
      SELECT MEMBER_NAME
                  ,MEMBER_TYPE_DESC
                  ,MEMBER_STATE_DESC
      FROM SYS.DM_HADR_CLUSTER_MEMBERS   

/*MONITORACAO - OPERATIONAL_STATE_DESC <> ONLINE E NULL 
RECOVERY_HEALTH_DESC <> ONLINE E NULL 
SYNCHRONIZATION_HEALTH_DESC <> HEALTHY
CONNECTED_STATE_DESC <> CONNECTED
LAST_CONNECT_ERROR_TIMESTAMP < 5 MIN
*/

      SELECT REPLICA_SERVER_NAME
            ,OPERATIONAL_STATE_DESC
            ,RECOVERY_HEALTH_DESC
            ,SYNCHRONIZATION_HEALTH_DESC
            ,CONNECTED_STATE_DESC
            ,LAST_CONNECT_ERROR_TIMESTAMP
      FROM SYS.DM_HADR_AVAILABILITY_REPLICA_STATES TB1
      INNER JOIN SYS.DM_HADR_NAME_ID_MAP TB2
      ON TB1.GROUP_ID=TB2.AG_ID
      INNER JOIN SYS.DM_HADR_AVAILABILITY_REPLICA_CLUSTER_STATES TB3
      ON TB3.REPLICA_ID=TB1.REPLICA_ID

/*MONITORACAO - MEMBER_STATE_DESC <> UP*/

      
      SELECT MEMBER_NAME
                  ,MEMBER_TYPE_DESC
                  ,MEMBER_STATE_DESC
      FROM SYS.DM_HADR_CLUSTER_MEMBERS

/************************************************************************************************************/
/************************************************************************************************************/

/*VERIFICA LISTENER STATE*/

      SELECT LISTENER_ID
                  ,IP_ADDRESS
                  ,TYPE_DESC
                  ,STATE_DESC
                  ,START_TIME
      FROM SYS.DM_TCP_LISTENER_STATES

/*MONITORACAO - STATE_DESC <> ONLINE*/

      SELECT LISTENER_ID
                  ,STATE_DESC
      FROM SYS.DM_TCP_LISTENER_STATES
>>>>>>> d4022b1c698892c56d61a9072b03678cdc0fa4fe
