/*
USE MASTER
GO
DROP DATABASE DB_TESTE
GO
*/
SET NOCOUNT ON;
GO

CREATE DATABASE DB_TESTE;
GO
PRINT 'DATABASE CREATED - ' + CONVERT(VARCHAR, GETDATE(), 121)
PRINT ' ' 

USE DB_TESTE;

CREATE TABLE TB_TESTE(
	DS VARCHAR(100),
	DT DATETIME
)
GO
PRINT 'TABLE CREATED ---- ' + CONVERT(VARCHAR, GETDATE(), 121)
PRINT ' ' 

DECLARE @I INT
 
SET @I = 1

WHILE ( @I <= 2000000 )
  BEGIN
      INSERT INTO TB_TESTE (ds, dt)
      VALUES     ('teste' + CAST(@I AS VARCHAR(10)), Getdate())
	  IF @I % 100000 = 0
	  BEGIN
	     PRINT CAST(@I AS VARCHAR) + ' ROWS INSERTED - ' + CONVERT(VARCHAR, GETDATE(), 121)
	  END
      SET @I = @I + 1
  END
  PRINT ' ' 
GO
PRINT 'ROWS INSERTED ---- ' + CONVERT(VARCHAR, GETDATE(), 121)
PRINT ' ' 

SELECT * FROM TB_TESTE
WHERE DS LIKE '%5%' OR DS LIKE '%8%'
ORDER BY 1 DESC
GO
PRINT 'ROWS SELECTED ---- ' + CONVERT(VARCHAR, GETDATE(), 121)
PRINT ' ' 

UPDATE TB_TESTE
SET DS = DS + ' - ' + DS
WHERE DS LIKE '%6%' OR DS LIKE '%2%'
GO
PRINT 'ROWS UPDATED ----- ' + CONVERT(VARCHAR, GETDATE(), 121)
PRINT ' ' 