CREATE TRIGGER [User_Logon] 
      ON ALL SERVER
      FOR LOGON
AS
IF UPPER(LTRIM(RTRIM(SUSER_NAME()))) <> 'SA'
BEGIN
                IF  (SELECT COUNT(*) FROM MASTER.DBO.LELIS_ACESSO_BD WHERE UPPER(RTRIM(LTRIM(USUARIO)))=UPPER(LTRIM(RTRIM(SUSER_NAME()))) AND UPPER(LTRIM(RTRIM(APLICATIVO)))=UPPER(LTRIM(RTRIM(APP_NAME())))) < 1
                               AND
                               (SELECT COUNT(*) FROM MASTER.DBO.LELIS_ACESSO_BD WHERE UPPER(RTRIM(LTRIM(USUARIO)))='TODOS' AND UPPER(LTRIM(RTRIM(APLICATIVO)))=UPPER(LTRIM(RTRIM(APP_NAME())))) < 1
                               AND   
                               (SELECT COUNT(*) FROM MASTER.DBO.LELIS_ACESSO_BD WHERE UPPER(RTRIM(LTRIM(USUARIO)))=UPPER(LTRIM(RTRIM(SUSER_NAME()))) AND UPPER(LTRIM(RTRIM(APLICATIVO)))='TODOS') < 1
                               AND
                               (SELECT COUNT(*) FROM MASTER.DBO.LELIS_ACESSO_BD WHERE UPPER(RTRIM(LTRIM(USUARIO)))= UPPER(LTRIM(RTRIM(SUSER_NAME()))) AND UPPER(LTRIM(RTRIM(APLICATIVO))) = 'SQL Server Profiler' AND UPPER(LTRIM(RTRIM(APP_NAME()))) LIKE 'SQL Server Profiler%') < 1
                BEGIN
                                 -- BLOQUEIA CONEXÃO
                                 ROLLBACK
                END
END

-- BLOQUEIA ACESSO AO DATASYNC SE A MÁQUINA NÃO FOR O SERVIDOR DO DATASYNC, MONITORAMENTO OU A MÁQUINA DO BRUNO
IF UPPER(LTRIM(RTRIM(APP_NAME()))) LIKE '%DATASYNC%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'LAP-BRUNOSILVA%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'LAP-TIAGO%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SRV-DATASYNC%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'MONITORAMENTO%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SRVMSP002%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'NOTE-LEANDRO%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SRVMSP027%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SANDRO--TI%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'JeffersonNunes%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SRVMSP032%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE '019838-NB%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE '020545-NB%'
                AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'RESTOQUETS01%'
                
BEGIN
                ROLLBACK
END

-- Não deixar logar com o ETL de outro computador
IF UPPER(LTRIM(RTRIM(APP_NAME()))) LIKE '%LinxETL%' AND UPPER(LTRIM(RTRIM(HOST_NAME()))) NOT LIKE 'SRVMSP027%'
BEGIN
                ROLLBACK
END

