USE HOSPITALAR_COP

DECLARE @DB_NOME VARCHAR(100)
DECLARE @NM_TABELA VARCHAR(100)
DECLARE @NM_COLUNA  VARCHAR(100)
DECLARE @COL_DATATYPE  VARCHAR(100)
DECLARE @COL_LEN INT

SET @DB_NOME = 'HOSPITALAR_COP'

DECLARE CUR_TABELAS CURSOR FOR

	SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_CATALOG = @DB_NOME AND
	TABLE_NAME NOT LIKE 'BI_%' AND
	TABLE_NAME NOT IN ('PAGAR_RECEBER', 'TABELA_INSUMO_VALOR', 'ACESSO_DROGA') AND
	--DATA_TYPE = 'VARCHAR' AND
	COLLATION_NAME <> 'LATIN1_GENERAL_CI_AS'
	ORDER BY TABLE_NAME

OPEN CUR_TABELAS

FETCH NEXT FROM CUR_TABELAS
INTO @NM_TABELA

WHILE @@FETCH_STATUS = 0
    BEGIN
		DECLARE CUR_COLUNAS CURSOR FOR
			SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS
			WHERE 
			TABLE_CATALOG = @DB_NOME AND
			TABLE_NAME = @NM_TABELA AND
			--COLUMN_NAME NOT LIKE '%_OBS' AND
			--COLUMN_NAME NOT LIKE '%_CD' AND
			--DATA_TYPE = 'VARCHAR' AND
			COLLATION_NAME <> 'LATIN1_GENERAL_CI_AS'
			ORDER BY TABLE_NAME

		OPEN CUR_COLUNAS

		FETCH NEXT FROM CUR_COLUNAS
		INTO @NM_COLUNA, @COL_DATATYPE, @COL_LEN
		WHILE @@FETCH_STATUS = 0
			BEGIN 
PRINT @NM_TABELA
PRINT @NM_COLUNA
PRINT @COL_LEN
PRINT '----------------------------'
--EXEC('ALTER TABLE  ' + @NM_TABELA + ' ALTER COLUMN ' + @NM_COLUNA + ' ' + @COL_DATATYPE + '(' + @COL_LEN + ')COLLATE LATIN1_GENERAL_CI_AS NULL')
				FETCH NEXT FROM CUR_COLUNAS
    			INTO @NM_COLUNA, @COL_DATATYPE, @COL_LEN
			END
			CLOSE CUR_COLUNAS
			DEALLOCATE CUR_COLUNAS

        FETCH NEXT FROM CUR_TABELAS
    	INTO @NM_TABELA
	END

CLOSE CUR_TABELAS
DEALLOCATE CUR_TABELAS
