DECLARE @NM_TABELA VARCHAR(40)
DECLARE @NM_TABELA_PESQ VARCHAR(100)

SET @NM_TABELA_PESQ = 'COMPARA'

DECLARE CUR_TABELAS CURSOR FOR

	SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME LIKE '%'+@NM_TABELA_PESQ+'%'


OPEN CUR_TABELAS

FETCH NEXT FROM CUR_TABELAS
INTO @NM_TABELA

WHILE @@FETCH_STATUS = 0
    BEGIN
    	EXEC('DROP TABLE ' + @NM_TABELA)
        FETCH NEXT FROM CUR_TABELAS
    	INTO @NM_TABELA

END

CLOSE CUR_TABELAS
DEALLOCATE CUR_TABELAS

