ALTER TABLE TRANSPORTPROVIDERSXAPPS NOCHECK CONSTRAINT FK_APPS_TRANSPROVIDERSXAPPS
ALTER TABLE TRANSPORTPROVIDERSXAPPS NOCHECK CONSTRAINT FK_APP_TPXAPP
ALTER TABLE APPLICATIONSTRINGS NOCHECK CONSTRAINT FK_APPS_APPLICATIONSTRINGS
ALTER TABLE CARDIMAGESXAPPLICATIONS NOCHECK CONSTRAINT FK_APPS_CARDIMAGESXAPPS
ALTER TABLE CARDTYPESXAPPSSECTORS NOCHECK CONSTRAINT FK_APP_CTYAPPSEC
ALTER TABLE RECHARGEORDERDT NOCHECK CONSTRAINT FK_APP_ROD
ALTER TABLE RELOADPERIODDT NOCHECK CONSTRAINT FK_APPS_RELOADPERIODDT
ALTER TABLE PROVXPROVTYPESXAPPS NOCHECK CONSTRAINT FK_APPS_PROVXPROVTYPESXAPPS
ALTER TABLE STUDENTTYPES NOCHECK CONSTRAINT FK_STUTP_APP
ALTER TABLE LINEPRICES NOCHECK CONSTRAINT FK_LINEPRICES_APPLICATIONS
ALTER TABLE TRIPDT NOCHECK CONSTRAINT FK_EXTAPP_TDT
ALTER TABLE TRANSPORTPROVIDERSXAPPS NOCHECK CONSTRAINT FK_APPS_TRANSPROVIDERSXAPPS
ALTER TABLE TRANSPORTPROVIDERSXAPPS NOCHECK CONSTRAINT FK_APP_TPXAPP


UPDATE TRANSPORTPROVIDERSXAPPS
SET [ISS_ID] = 70

UPDATE 
SELECT * FROM [APPLICATIONS]
SET [ISS_ID] = 70

UPDATE APPLICATIONS
SET APP_ID = 429
WHERE APP_ID = 417

UPDATE TRIPDT
SET [APP_ISS_ID] = 70

UPDATE EXTERNALAPPLICATIONS
SET EXTAPP_ISS_ID= 70

UPDATE STUDENTTYPES
SET ISS_ID = 70

ALTER TABLE TRANSPORTPROVIDERSXAPPS CHECK CONSTRAINT FK_APPS_TRANSPROVIDERSXAPPS
ALTER TABLE TRANSPORTPROVIDERSXAPPS CHECK CONSTRAINT FK_APP_TPXAPP
ALTER TABLE APPLICATIONSTRINGS CHECK CONSTRAINT FK_APPS_APPLICATIONSTRINGS
ALTER TABLE CARDIMAGESXAPPLICATIONS CHECK CONSTRAINT FK_APPS_CARDIMAGESXAPPS
ALTER TABLE CARDTYPESXAPPSSECTORS CHECK CONSTRAINT FK_APP_CTYAPPSEC
ALTER TABLE RECHARGEORDERDT CHECK CONSTRAINT FK_APP_ROD
ALTER TABLE RELOADPERIODDT CHECK CONSTRAINT FK_APPS_RELOADPERIODDT
ALTER TABLE PROVXPROVTYPESXAPPS CHECK CONSTRAINT FK_APPS_PROVXPROVTYPESXAPPS
ALTER TABLE STUDENTTYPES CHECK CONSTRAINT FK_STUTP_APP
ALTER TABLE LINEPRICES CHECK CONSTRAINT FK_LINEPRICES_APPLICATIONS
ALTER TABLE TRIPDT CHECK CONSTRAINT FK_EXTAPP_TDT
ALTER TABLE TRANSPORTPROVIDERSXAPPS CHECK CONSTRAINT FK_APPS_TRANSPROVIDERSXAPPS
ALTER TABLE TRANSPORTPROVIDERSXAPPS CHECK CONSTRAINT FK_APP_TPXAPP
