SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME NOT IN(
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'PRIMARY KEY')
AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME
