DBCC SHOWCONTIG ('POS_SESSIONXTRANMT')
DBCC INDEXDEFRAG (db_mercury, POS_SESSIONXTRANMT,PK_PSTMT)
select count(*) from POS_SESSIONXTRANMT


DBCC SHOWCONTIG ('POS_PRODUCTS')
DBCC INDEXDEFRAG (db_mercury, POS_SESSIONXTRANMT,PK_PSTMT)
select count(*) from POS_PRODUCTS

 
DBCC SHOWCONTIG ('POS_MAINGROUPS')
DBCC INDEXDEFRAG (db_mercury, POS_MAINGROUPS,)
select count(*) from POS_MAINGROUPS


DBCC SHOWCONTIG ('POS_TRANDT')
DBCC INDEXDEFRAG (db_mercury, POS_TRANMT,IDX_POS_TRANMTXPAYMENTMODES)
DBCC INDEXDEFRAG (db_mercury, POS_TRANMT,INDEX_CLOSING)
DBCC INDEXDEFRAG (db_mercury, POS_TRANMT,ix_pdcode_postranmt)
DBCC INDEXDEFRAG (db_mercury, POS_TRANMT,PK_POS_TRANMT)
DBCC INDEXDEFRAG (db_mercury, POS_TRANDT,IDX_POS_TRANDT)
DBCC INDEXDEFRAG (db_mercury, POS_TRANDT,IX_POS_TRANDT)
DBCC INDEXDEFRAG (db_mercury, POS_TRANDT,PK_POS_TRANDT)
DBCC INDEXDEFRAG (db_mercury, POS_TRANDT,XIF2POS_TRANDT)
select count(*) from POS_TRANMT


DBCC SHOWCONTIG ('POS_TRANMT')
select count(*) from POS_TRANMT




