--Servidor: 200.228.66.204
--Usuário : sa
--Senha   : e26f16

USE DB_MERCURY_JUN

INSERT INTO CRTEXPORTDT (  
            EVI_CODE, EVI_VERSION, TP_ID, PRV_ID, ROM_TRANID, ROM_SEQNBR, ROD_SEQNBR, CED_TRANOWNER, CED_RSN, 
            CED_CREDITS, CED_OPCODE, CED_ROMMEMODATE, CED_ROMEXPDATE, CED_REGDATE, CED_REGUSER )              
            SELECT EVI_CODE, 1 EVI_VERSION, RI.TP_ID, PRV_ID, ROM_TRANID, ROM_SEQNBR, ROD_SEQNBR, CED_TRANOWNER, 
	    CED_RSN, CED_CREDITS, CED_OPCODE, CED_ROMMEMODATE, CED_ROMEXPDATE, CED_REGDATE, CED_REGUSER               
            FROM CRTXSCM
            JOIN ( SELECT DISTINCT RITP.TP_ID , RI.USR_ID
                   FROM RECHARGEINFO RI
                   JOIN RECHARGEINFOXTRANSPPROVIDERS RITP ON RI.RI_ID = 
RITP.RI_ID
           WHERE  RI.RI_STATUS =  'A'  AND RITP.RITP_STATUS = 'A' ) RI ON 
RI.USR_ID = CRTXSCM.USR_ID
WHERE CRTXSCM.ISS_ID       = 42
  AND CRTXSCM.CD_ID        = 4
  AND CRTXSCM.CRD_SNR      = 179816
  AND CRTXSCM.CI_ID        = 1
  AND CRTXSCM.APP_ISS_ID   = 42
  AND CRTXSCM.APP_ID       = 400
  AND CRTXSCM.CIAPP_SEQNBR = 1
  AND CRTXSCM.CAC_SEQNBR   = 8
  AND CRTXSCM.EVI_VERSION   = 412

--=============================================================================================

CREATE 
  INDEX [IDX_CEMT_CEDT] ON [dbo].[CRTEXPORTDT] ([EVI_CODE], [EVI_VERSION])

CREATE 
  INDEX [IDX_ROD_CEDT] ON [dbo].[CRTEXPORTDT] ([ROM_TRANID], [PRV_ID], [ROM_SEQNBR], [ROD_SEQNBR])

CREATE 
  INDEX [IDX_TP_CEDT] ON [dbo].[CRTEXPORTDT] ([TP_ID])

CREATE 
  INDEX [idx_crtXSCM_SCM] ON [dbo].[CRTxSCM] ([ISS_ID], [CD_ID], [CRD_SNR], [CI_ID], [APP_ISS_ID], [APP_ID], [CIAPP_SEQNBR], [CAC_SEQNBR], [EVI_VERSION])

CREATE 
  INDEX [IDX_RECHINFO_RECHINFOXTP] ON [dbo].[RECHARGEINFOXTRANSPPROVIDERS] ([RI_ID])

CREATE 
  INDEX [IDX_TRANSPROVIDERS_RECHINFOXTP] ON [dbo].[RECHARGEINFOXTRANSPPROVIDERS] ([TP_ID])
