SELECT CONTATO.CONT_ID, cont_nm Nome, cont_empresa Empresa, END_LOGRADOURO, TEL_NUMERO
FROM   CONTATO 
	LEFT JOIN VINC_CONT_END ON VINC_CONT_END.CONT_ID = CONTATO.CONT_ID
	LEFT JOIN ENDERECO      ON VINC_CONT_END.END_ID  = ENDERECO.END_ID
	LEFT JOIN VINC_CONT_TEL ON VINC_CONT_TEL.CONT_ID = CONTATO.CONT_ID
	LEFT JOIN TELEFONE	ON VINC_CONT_TEL.TEL_ID  = TELEFONE.TEL_ID