DELETE FROM  COTACAO_INSUMO
DELETE FROM  COTACAO_FORNECEDOR_PROPOSTA
DELETE FROM  SOLICITACAO_COMPRA_INSUMO
ALTER TABLE  ITENS_ENTREGA DISABLE TRIGGER TriggerITEMENTREGAdelete
DELETE FROM  ITENS_ENTREGA
ALTER TABLE  ITENS_ENTREGA ENABLE TRIGGER TriggerITEMENTREGAdelete
DELETE FROM  ENTREGA
DELETE FROM  COMPRA
DELETE FROM  COTACAO
DELETE FROM  EVENTO_FARM_ETIQUETA

DELETE FROM  PACIENTE_MEDICO
DELETE FROM  RESPONSAVEL_PACIENTE
DELETE FROM  FAMILIA_PACIENTE
DELETE FROM  PACIENTE_CONVENIO
DELETE FROM ENDERECO WHERE PAC_ID IS NOT NULL
DELETE FROM  INDICACAO
DELETE FROM  PACIENTE_SOCIO_ECONOMICO_RESPOSTA
DELETE FROM  PACIENTE_SOCIO_ECONOMICO
DELETE FROM  FAMILIA_PACIENTE
DELETE FROM ENDERECO WHERE PAC_ID IS NOT NULL
DELETE FROM  DOCUMENTO WHERE PAC_ID IS NOT NULL
DELETE FROM  PACIENTE_CONVENIO

alter table ESTORNO_EMISSAO disable trigger TriggerEstornoEmissaoDelete
DELETE FROM ESTORNO_EMISSAO
alter table ESTORNO_EMISSAO enable trigger TriggerEstornoEmissaoDelete

alter table ITENS_EMISSAO disable trigger TriggerItensEmissaoDelete
DELETE FROM  ITENS_EMISSAO
alter table ITENS_EMISSAO enable trigger TriggerItensEmissaoDelete

alter table EMISSAO disable trigger TriggerEmissaoDelete
DELETE FROM  EMISSAO
alter table EMISSAO enable trigger TriggerEmissaoDelete

DELETE FROM  CAPA_LOTE
DELETE FROM  CONTA_ITEM
DELETE FROM  CONTA

DELETE FROM  EVENTO_DADO_INTERNACAO
DELETE FROM  EVENTO_INTERNACAO
DELETE FROM  EVENTO_AMBULATORIO
DELETE FROM  EVENTO_INTERNACAO

DELETE FROM EXAME_RAD_LAUDO_ADENDO 

DELETE FROM  FICHA_DE_PRODUCAO_LABORATORIAL
DELETE FROM  RESULTADO_EXAME_RAD_MAMO_CATEGORIA
DELETE FROM  RESULTA_EXA_RAD_VERSUS_DICIONARIO
DELETE FROM  PAPA_LAUDO
DELETE FROM  RESULTADO_EXAME_LAB
DELETE FROM  RESULTADO_EXAME_RAD
DELETE FROM  RESULTADO_EXAME_ESP

DELETE FROM  RESULTADO_EXA_LAB_VERSUS_DICIONARIO
DELETE FROM  RESULTADO_EXA_RAD_VERSUS_DICIONARIO
DELETE FROM  RESULTADO_EXA_ESP_VERSUS_DICIONARIO

DELETE FROM  RESULTADO_EXAME_LAB_LAUDO
DELETE FROM  RESULTADO_EXAME_RAD_LAUDO
DELETE FROM  RESULTADO_EXAME_ESP_LAUDO

DELETE FROM  RESULTADO_EXAME_LABORATORIAL_ASSINATURA
DELETE FROM  RESULTADO_EXAME_LAB_ASSINATURA
DELETE FROM  RESULTADO_EXAME_RAD_ASSINATURA
DELETE FROM  RESULTADO_EXAME_ESPECIAL_ASSINATURA

DELETE FROM  GUIA_SERVICO_ITEM
DELETE FROM  GUIA_SERVICO
DELETE FROM  GUIA

DELETE FROM  ITENS_SOLICITACAO_EXAME_LAB
DELETE FROM  ITENS_SOLICITACAO_EXAME_RAD
DELETE FROM  ITENS_SOLICITACAO_EXAME_ESP

DELETE FROM  SOLICITACAO_EXAME_LABORATORIAL
DELETE FROM  SOLICITACAO_EXAME_RADIOLOGICO
DELETE FROM  SOLICITACAO_EXAME_ESPECIAL


DELETE FROM  TOTAL_HORA_PROFISSIONAL

DELETE FROM  AIH_PROCEDIMENTO
DELETE FROM  AIH_SERVICO
DELETE FROM  AIH_INTERNACAO
DELETE FROM  AIH_ACIDENTE_TRABALHO
DELETE FROM  AIH_PARTO
DELETE FROM  AIH


DELETE FROM  QUIMIOTERAPIA_MEDICAMENTO
DELETE FROM  QUIMIOTERAPIA
DELETE FROM  TRATAMENTO
DELETE FROM  RH_HATCHING_INDICACAO
DELETE FROM  RH_MEDICAO_RESULTADO
DELETE FROM  RH_MEDICAO_FORMA
DELETE FROM  RH_HATCHING
DELETE FROM  RH_ATRIBUTO_EMBRIAO
DELETE FROM  IMAGEM
DELETE FROM  RH_EMBRIAO
DELETE FROM  IMAGEM_EVOLUCAO
DELETE FROM  RH_TRATAMENTO_MEIO_CULTURA
DELETE FROM  RH_TRATAMENTO
DELETE FROM  RH_RESPOSTA


DELETE FROM  AGENDA_OBS
DELETE FROM  AGENDA

alter table APAC_QT disable trigger DeleteBackupApacQT
DELETE FROM  APAC_QT
alter table APAC_QT disable trigger DeleteBackupApacQT

DELETE FROM  APAC_PROCEDIMENTO
DELETE FROM  APAC_RTX
DELETE FROM  APAC_EXAME_ESPECIAL
DELETE FROM  APAC_EXAME_RADIOLOGICO
DELETE FROM  APAC_CONTA_ITEM
DELETE FROM  APAC_EXAME_ESPECIAL
DELETE FROM APAC_EXAME_LABORATORIAL
DELETE FROM  APAC

DELETE FROM  OCUPACAO
DELETE FROM  OCUPACAO_DIA

DELETE FROM  BS_RESPOSTAS_ANAMNESE
DELETE FROM  EVENTO_BANCO_SANGUE
DELETE FROM  SINAIS_VITAIS

DELETE FROM  SOLICITACAO_INTERNACAO
DELETE FROM  EVOLUCAO_SINTOMA
DELETE FROM  TOXICIDADE_PACIENTE
DELETE FROM  EXAME_FISICO_PERGUNTA_PACIENTE
DELETE FROM  EXAME_FISICO
DELETE FROM  DIAGNOSTICO
DELETE FROM  PREVENCAO_CANCER
DELETE FROM  PREVENCAO_CANCER_RESPOSTA
DELETE FROM  PREVENCAO_CANCER_COMENTARIO
DELETE FROM  PREVENCAO_CANCER_PONTO
DELETE FROM  EVOLUCAO


DELETE FROM  ANTECEDENTE_PERGUNTA
DELETE FROM  ANTECEDENTE_DESCRITIVO

DELETE FROM PRESCRICAO_MEDICAMENTO
DELETE FROM  PRESCRICAO_DIETA
DELETE FROM PRESCRICAO_IV_ITEM
DELETE FROM PRESCRICAO_IV
DELETE FROM PRESCRICAO_NPP_ITEM
DELETE FROM PRESCRICAO_NPP
DELETE FROM  PRESCRICAO
 
DELETE FROM  PACIENTE_FLUXO_PRONTUARIO

DELETE FROM  ESTORNO_EMISSAO

alter table ESTORNO_GERAL disable trigger TriggerEstornoGeralDelete
DELETE FROM  ESTORNO_GERAL
alter table ESTORNO_GERAL disable trigger TriggerEstornoGeralDelete

DELETE FROM  ESTORNO

DELETE FROM PRONTUARIO_SOLICITACAO_ITEM
DELETE FROM FICHA_RESUMO_DIAGNOSTICO_ADM

DELETE FROM EVENTO_EXTERNO

DELETE FROM FICHA_RESUMO
DELETE FROM PACIENTE_ENTIDADE
DELETE FROM PACIENTE WHERE TPAC_ID = 1

alter table ITENS_ENTREGA disable trigger TriggerItemEntregaDelete
DELETE FROM  ITENS_ENTREGA
alter table ITENS_ENTREGA enable trigger TriggerItemEntregaDelete

DELETE FROM  ENTREGA


alter table ITENS_QUEBRA disable trigger TriggerItemQuebraDelete
DELETE FROM  ITENS_QUEBRA
alter table ITENS_QUEBRA enable trigger TriggerItemQuebraDelete

DELETE FROM  QUEBRA

alter table ITENS_TRANSFERENCIA disable trigger TriggerItemTransferDelete
DELETE FROM  ITENS_TRANSFERENCIA
alter table ITENS_TRANSFERENCIA enable trigger TriggerItemTransferDelete

DELETE FROM  TRANSFERENCIA

DELETE FROM  APAC
DELETE FROM  CAIXA
DELETE FROM  CAIXA_USUARIO

DELETE FROM  SUS_BPA_ITENS_RAD
DELETE FROM  SUS_BPA_ITENS_LAB
DELETE FROM  SUS_BPA_ITENS_ESP

DELETE FROM TOTALIZADOR_SADT_RAD_DIA
DELETE FROM TOTALIZADOR_SADT_LAB_DIA
DELETE FROM TOTALIZADOR_SADT_ESP_DIA
 
DELETE FROM  MEDICO_ESPECIALIDADE
DELETE FROM  USUARIO_ENTIDADE
DELETE FROM  INVENTARIO_ITEM
DELETE FROM  INVENTARIO
DELETE FROM  USUARIO_MUNICIPIO
DELETE FROM  USUARIO_CENTRO_CUSTO_COMPRA
DELETE FROM  USUARIO_CENTRO_CUSTO
DELETE FROM  USUARIO WHERE USU_LOGIN <> 'T'
DELETE FROM  MEDICO_CLINICA
DELETE FROM  MEDICO

DELETE FROM  PROFISSIONAL
DELETE FROM  TOTALIZADOR_AMBULATORIO
DELETE FROM  CLINICA
DELETE FROM  ITENS_COMPRA
DELETE FROM  ITENS_COMPRA_SERVICO
DELETE FROM  ITENS_COMPRA_IMOBILIZADO
DELETE FROM  COMPRA
DELETE FROM  SOLICITACAO_COMPRA_IMOBILIZADO
DELETE FROM  SOLICITACAO_COMPRA_INSUMO
DELETE FROM  SOLICITACAO_COMPRA_SERVICO
DELETE FROM  SOLICITACAO_COMPRA
DELETE FROM  CENTRO_CUSTO_TETO

DELETE FROM  CONFIG_EXAME_ESPECIAL
DELETE FROM  EXAMES_ESPECIAIS_PRESTADOR
DELETE FROM  EXAME_ESPECIAL_DICIONARIO
DELETE FROM  EXAMES_ESPECIAIS

DELETE FROM  CONFIG_EXAME_LABORATORIAL
DELETE FROM  EXAME_LABORATORIAL_LIMITE
DELETE FROM  FAIXA_ETARIA
DELETE FROM  EXAMES_LABORATORIAIS_PRESTADOR
DELETE FROM  EXAME_LABORATORIAL_METODOLOGIA
DELETE FROM  DISPOSITIVO_LABORATORIAL_EXAME
DELETE FROM EXAME_LABORATORIAL_DICIONARIO
DELETE FROM  EXAMES_LABORATORIAIS

DELETE FROM  CONFIG_EXAME_RADIOLOGICO
DELETE FROM EXAMES_RADIOLOGICOS_PRESTADOR
DELETE FROM EXAME_RADIOLOGICO_DICIONARIO
DELETE FROM  EXAMES_RADIOLOGICOS

DELETE FROM  PROGRAMACAO_AGENDA
DELETE FROM  PROGRAMACAO_AGENDA_PADRAO
DELETE FROM  TOTALIZADOR_AGENDA
DELETE FROM  POSTO_RECEPCAO_AGENDA_SALA
DELETE FROM  SALA
DELETE FROM  TOTALIZADOR_AGENDAMENTO
DELETE FROM  REGULACAO_SETOR
DELETE FROM  TIPO_SALA

DELETE FROM  POSTO_ENFERMAGEM_CENTRO_CUSTO
DELETE FROM  LEITO
DELETE FROM  TOTALIZADOR_OCUPACAO_DIA
DELETE FROM  TOTALIZADOR_LEITO_DIA
DELETE FROM  TOTALIZADOR_PRESCRICAO_DIA
DELETE FROM  SAE_TURNO 
DELETE FROM  CONFIGURACAO_SERVICO_POSTO
DELETE FROM  POSTO_DE_ENFERMAGEM

DELETE FROM  PAGAR_RECEBER
DELETE FROM RH_DESPESA_CENTRO_CUSTO

DELETE FROM  TOTALIZADOR_CONSUMO_DIA
DELETE FROM  TOTALIZADOR_ESTOQUE
DELETE FROM  TOTALIZADOR_ESTOQUE_DIA
DELETE FROM  ESTOQUE_POSICAO
DELETE FROM  INSUMO_ESTOQUE_PARAMETRO
DELETE FROM  SOLICITACAO_TRANSFERENCIA_ITEM
DELETE FROM  SOLICITACAO_TRANSFERENCIA
DELETE FROM  SERVICO_KIT
DELETE FROM  INSUMO_TABELA
DELETE FROM  INSUMO_FABRICANTE
DELETE FROM  ESTOQUE_LOTE
DELETE FROM  INSUMO_FORNECEDOR
DELETE FROM  PROTOCOLO_DIA_MEDICAMENTO
DELETE FROM  PROTOCOLO_GERAL_DIA_MEDICAM
DELETE FROM  INSUMO
DELETE FROM  CONFIGURACAO_SERVICO_SUS
DELETE FROM  CONFIGURACAO_SERVICO_CONVENIO
DELETE FROM  CONFIGURACAO_SERVICO_SUS_AIH
DELETE FROM  SUBGRUPO_SERVICO
DELETE FROM  GRUPO_SERVICO
DELETE FROM  TIPO_SERVICO
DELETE FROM  ESTOQUE


DELETE FROM  CENTRO_CUSTO_LOCAL
DELETE FROM  CENTRO_CUSTO
DELETE FROM TOTALIZADOR_CONSUMO
DELETE FROM  COBERTURA_REGRA
DELETE FROM  COBERTURA


ALTER TABLE CONFIGURADOR ALTER COLUMN PCONV_ID_DEFAULT INT NULL
UPDATE CONFIGURADOR SET PCONV_ID_DEFAULT = NULL
DELETE FROM TOTALIZADOR_CONSUMO_DIA
DELETE FROM TOTALIZADOR_PROCEDIMENTO
DELETE FROM  PLANO_CONVENIO

DELETE FROM TOTALIZADOR_ESTOQUE
DELETE FROM  ESTOQUE_POSICAO
DELETE FROM  ESTOQUE_LOTE
DELETE FROM  ESTOQUE

DELETE FROM  PACIENTE

DELETE FROM  COTACAO_INSUMO
DELETE FROM  UNIDADE_CONVERSAO
DELETE FROM  INSUMO_TABELA
DELETE FROM  INSUMO_FORNECEDOR
DELETE FROM  INSUMO_FABRICANTE
DELETE FROM  INSUMO

DELETE FROM PROTOCOLO_PEDIATRICO_ESQUEMA_ITEM
DELETE FROM SINAL_VITAL_CADASTRO
DELETE FROM PROTOCOLO_PED_DIA_MED_FAIXA
DELETE FROM PROTOCOLO_PED_DIA_MEDICAMENTO
DELETE FROM MEDICAMENTO_DILUENTE
DELETE FROM NPP_ITEM
DELETE FROM CONTROLA_DOSE
DELETE FROM MEDICAMENTO_VIA_CTR_DOSE
DELETE FROM MEDICAMENTO_VIA
DELETE FROM MEDICAMENTO
DELETE FROM  UNIDADES


DELETE FROM  PACIENTE
DELETE FROM  PROFISSIONAL
DELETE FROM  MEDICO
DELETE FROM  MEDICO_ESPECIALIDADE
DELETE FROM  MEDICO_CLINICA
DELETE FROM  PAGAR_RECEBER

  
DELETE FROM  CONFIGURACAO_SERVICO_CONVENIO
DELETE FROM  CAIXA_CONTA_CORRENTE_SALDO
DELETE FROM  ENDERECO
DELETE FROM  TABELA_AMB_VALOR
DELETE FROM  TABELA_INSUMO_VALOR
DELETE FROM  DOCUMENTO
DELETE FROM  RESPONSAVEL_PACIENTE
DELETE FROM  ACESSO_DROGA
DELETE FROM  CAD_CAIXA
DELETE FROM  CAIXA
DELETE FROM  CAIXA_CONTA_CORRENTE
DELETE FROM  CAIXA_USUARIO
DELETE FROM  COBERTURA_REGRA
DELETE FROM  COBERTURA
DELETE FROM  DIAGNOSTICO
DELETE FROM  ESTADIO
DELETE FROM  ESTADIO_COMBINACAO
DELETE FROM  ESTADIO_SISTEMA
DELETE FROM  ITENS_EMISSAO
DELETE FROM  EMISSAO
DELETE FROM  ESTOQUE
DELETE FROM  ESTOQUE_CONFIGURACAO
DELETE FROM  ESTOQUE_LOTE
DELETE FROM  ESTOQUE_POSICAO
DELETE FROM  EXAME_LAB_ITENS
DELETE FROM  ITENS_SOLICITACAO_EXAME_LAB
DELETE FROM  ITENS_SOLICITACAO_EXAME_RAD
DELETE FROM  ITENS_SOLICITACAO_EXAME_ESP
DELETE FROM  SOLICITACAO_EXAME_LABORATORIAL
DELETE FROM  SOLICITACAO_EXAME_RADIOLOGICO
DELETE FROM  SOLICITACAO_EXAME_ESPECIAL
DELETE FROM  EXAMES_ESPECIAIS
DELETE FROM  EXAMES_LABORATORIAIS
DELETE FROM  EXAMES_RADIOLOGICOS
DELETE FROM  FAMILIA_PACIENTE


DELETE FROM CONFIGURACAO_SERVICO_SUS
DELETE FROM CONFIGURACAO_SERVICO_SUS_AIH


DELETE FROM  SERVICO_KIT
DELETE FROM  SERVICO
DELETE FROM  SUBGRUPO_SERVICO
DELETE FROM  GRUPO_SERVICO
DELETE FROM  TIPO_SERVICO

DELETE FROM  HORARIO_PADRAO
DELETE FROM  INSUMO_FABRICANTE
DELETE FROM  INSUMO_FORNECEDOR
DELETE FROM  INSUMO_RECONSTITUICAO
DELETE FROM  INSUMO_TABELA
DELETE FROM  INSUMO
DELETE FROM  NPP_ITEM
DELETE FROM  MEDICAMENTO
DELETE FROM  GRUPO_MEDICAMENTO

DELETE FROM  MEDICO_ESPECIALIDADE
DELETE FROM  PACIENTE_CONVENIO
DELETE FROM  PACIENTE_INDICACAO
DELETE FROM  PACIENTE_MEDICO
DELETE FROM  PACIENTE_SOCIO_ECONOMICO


DELETE FROM PESSOA_JURIDICA_PLANO_CONTA_GERENCIAL
DELETE FROM CONTRATO
DELETE FROM  PESSOA_JURIDICA


DELETE FROM  PROTOCOLO_DIA_MEDICAMENTO
DELETE FROM  PROTOCOLO_DIA_EXAME
DELETE FROM  PROTOCOLO_DIA
DELETE FROM  PROTOCOLO


DELETE FROM  QUALIFICADOR_INSUMO
DELETE FROM  SERVICO
DELETE FROM  SERVICO_KIT
DELETE FROM  TABELA
DELETE FROM  TABELA_AMB_COMERCIAL
DELETE FROM  TABELA_AMB_VALOR
DELETE FROM  TABELA_INSUMO
DELETE FROM  TABELA_INSUMO_VALOR
DELETE FROM  TIPO_VIA
DELETE FROM  TIPO_TRATAMENTO

DELETE FROM  UNIDADES
DELETE FROM  TIPO_SALA
DELETE FROM  TIPO_MEDICAMENTO
DELETE FROM  SUBGRUPO_SERVICO
DELETE FROM  GRUPO_SERVICO
DELETE FROM  TIPO_SERVICO
DELETE FROM  CUSTOM_EXAME_FISICO
DELETE FROM  EXAME_FISICO_ORGAO_FRASE
DELETE FROM  EXAMES_PADROES
DELETE FROM  GRUPO_MEDICAMENTO
DELETE FROM  EXAME_FISICO

DELETE FROM  EXAMES_PADROES
DELETE FROM  CUSTOM_EXAME_FISICO
DELETE FROM  EXAMES_PADROES
DELETE FROM  PLANO_CONTA
DELETE FROM  UNIDADES
DELETE FROM  QUIMIOTERAPIA_MEDICAMENTO
DELETE FROM  QUIMIOTERAPIA
DELETE FROM  PROTOCOLO_DIA
DELETE FROM  TRATAMENTO
DELETE FROM  PROTOCOLO

DELETE FROM  SINAIS_VITAIS
DELETE FROM  EVOLUCAO
DELETE FROM  DOCUMENTO
DELETE FROM  ENDERECO
DELETE FROM  AMB_PROCEDIMENTO
DELETE FROM  AMB_GRUPO
DELETE FROM  AMB_ESPECIALIDADE
DELETE FROM  PROTOCOLO_PED_PATOLOGIA
DELETE FROM  ESTADIO_PEDIATRICO
DELETE FROM  ONCO_PED_DIAG_ESTADIO_TIPO
DELETE FROM  ONCO_PED_DIAG_REGIAO_CH
DELETE FROM  ONCO_PED_DIAGNOSTICO

DELETE FROM  CID
DELETE FROM  CID_MORFOLOGICO
DELETE FROM  MEDICO
DELETE FROM  PACIENTE
DELETE FROM  PLANO_CONVENIO
DELETE FROM  SIAB_FAMILIA_SE_RESPOSTA
DELETE FROM  SIAB_CMP_FAM_SOCIO_ECONOMICO
DELETE FROM  SIAB_CMP_FAM_TRANSPORTE
DELETE FROM  SIAB_CMP_FAM_DOENCA_PROCURA
DELETE FROM  SIAB_CMP_FAM_MEIO_COM
DELETE FROM  SIAB_CMP_FAM_GRUPO_COMUN
DELETE FROM  SIAB_COMPET_FAMILIA
DELETE FROM  CONVENIO
DELETE FROM  PLANO_AGENDA




DELETE FROM [TOTALIZADOR_AGENDA] 
DELETE FROM [TOTALIZADOR_AGENDAMENTO] 
DELETE FROM [TOTALIZADOR_AIH] 
DELETE FROM [TOTALIZADOR_AMBULATORIO] 
DELETE FROM [TOTALIZADOR_APAC] 


DELETE FROM [TOTALIZADOR_BPA_ESP] 
DELETE FROM [TOTALIZADOR_BPA_IMG] 
DELETE FROM [TOTALIZADOR_BPA_LAB] 
DELETE FROM [TOTALIZADOR_CONSUMO] 
DELETE FROM [TOTALIZADOR_CONSUMO_DIA] 


DELETE FROM [TOTALIZADOR_ESTOQUE] 
DELETE FROM [TOTALIZADOR_ESTOQUE_DIA] 
DELETE FROM [TOTALIZADOR_ESTOQUE_DIA_LOG] 
DELETE FROM [TOTALIZADOR_LEITO_DIA] 
DELETE FROM [TOTALIZADOR_OCUPACAO_DIA] 


DELETE FROM [TOTALIZADOR_OCUPACAO_MES] 
DELETE FROM [TOTALIZADOR_PRESCRICAO_DIA] 
DELETE FROM [TOTALIZADOR_PRESCRICAO_DIA_LOG] 
DELETE FROM [TOTALIZADOR_PROCEDIMENTO] 
DELETE FROM [TOTALIZADOR_SADT_ESP_DIA] 


DELETE FROM [TOTALIZADOR_SADT_ESP_DIA_LOG] 
DELETE FROM [TOTALIZADOR_SADT_LAB_DIA] 
DELETE FROM [TOTALIZADOR_SADT_LAB_DIA_LOG] 
DELETE FROM [TOTALIZADOR_SADT_RAD_DIA] 
DELETE FROM [TOTALIZADOR_SADT_RAD_DIA_LOG] 




