IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[APB_REINDEX_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE APB_REINDEX_LOG(
	TABLE_CATALOG VARCHAR(50), 
	TABLE_SCHEMA VARCHAR(50), 
	TABLE_NAME VARCHAR(50), 
	TABLE_TYPE VARCHAR(50),
	REINDEX_DATE DATETIME,
	REINDEX_ID INT
)
GO

DECLARE @REINDEX_ID INT
DECLARE @TABLE_CATALOG VARCHAR(50), @TABLE_SCHEMA VARCHAR(50), @TABLE_NAME VARCHAR(50), @TABLE_TYPE VARCHAR(50)

SET @REINDEX_ID = (SELECT ISNULL(MAX(REINDEX_ID) + 1, 1)FROM APB_REINDEX_LOG)

DECLARE TableCursor CURSOR FOR
	SELECT * FROM information_schema.tables
	WHERE table_type = 'base table'  
		  and table_name not in('CARDUSAGE')
	ORDER BY TABLE_NAME

OPEN TableCursor

FETCH NEXT FROM TableCursor INTO @TABLE_CATALOG, @TABLE_SCHEMA, @TABLE_NAME, @TABLE_TYPE
WHILE @@FETCH_STATUS = 0
BEGIN
	DBCC DBREINDEX(@TABLE_NAME,' ',90)
	PRINT 'TABELA ' + @TABLE_NAME + ' REINDEXADA COM SUCESSO'
	INSERT INTO APB_REINDEX_LOG values(@TABLE_CATALOG, @TABLE_SCHEMA, @TABLE_NAME, @TABLE_TYPE, getdate(), @REINDEX_ID)
	FETCH NEXT FROM TableCursor INTO @TABLE_CATALOG, @TABLE_SCHEMA, @TABLE_NAME, @TABLE_TYPE
END

CLOSE TableCursor

DEALLOCATE TableCursor


SELECT * FROM APB_REINDEX_LOG