DECLARE @NM_TABELA VARCHAR(40)

DECLARE CUR_TABELAS CURSOR FOR

    SELECT OBJ.NAME FROM SYSOBJECTS OBJ
    
    JOIN SYSUSERS USR
    	ON OBJ.UID = USR.UID
    
    WHERE OBJ.XTYPE = 'U'

OPEN CUR_TABELAS

FETCH NEXT FROM CUR_TABELAS
INTO @NM_TABELA

WHILE @@FETCH_STATUS = 0
    BEGIN
    	TRUNCATE TABLE @NM_TABELA
        FETCH NEXT FROM CUR_TABELAS
    	INTO @NM_TABELA

END

CLOSE CUR_TABELAS
DEALLOCATE CUR_TABELAS