DECLARE I INT
SET I = 1
WHILE < 9999999

INSERT INTO TESTE (DS, DT) VALUES ('TESTE DEAO', GETDATE())

INSERT INTO TESTE (DS, DT) SELECT DS, DT FROM TESTE

CREATE TAB


SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM SYSFILEGROUPS