SELECT
  c1.table_name,
  c1.COLUMN_NAME,
  c1.DATA_TYPE,
  c2.table_name,
  c2.DATA_TYPE,
  c2.COLUMN_NAME
FROM      [INFORMATION_SCHEMA].[COLUMNS] c1
LEFT JOIN [INFORMATION_SCHEMA].[COLUMNS] c2 ON c1.COLUMN_NAME = c2.COLUMN_NAME
WHERE c1.TABLE_NAME = 'article'
  AND c2.TABLE_NAME = 'article2'
  AND c1.data_type <> c2.DATA_TYPE