@echo off
SET SERVIDOR=ANFLABANCO
SET DATABASE=HOSPITALAR
SET USUSQL=ANFLAHOSPITALAR
SET PWDSQL=ANFLAHOSPITALAR
SET CAMINHO_BAK=D:\XXX
SET ARQ_BAK=BACK_HOSPITALAR

del "%CAMINHO_BAK%\%ARQ_BAK%.BAK"
"C:\Arquivos de programas\Microsoft SQL Server\80\Tools\Binn\OSQL" -S %SERVIDOR% -U %USUSQL% -P %PWDSQL% -Q "BACKUP DATABASE %DATABASE% TO DISK ='%CAMINHO_BAK%\%ARQ_BAK%.BAK'"
"C:\Arquivos de programas\WinRAR\WinRAR.exe" a -u -r -dh -agYYYYMMMDD "%CAMINHO_BAK%\%ARQ_BAK%.rar" "%CAMINHO_BAK%\%ARQ_BAK%.BAK"
