SELECT COUNT(*) FROM TESTE

INSERT INTO TESTE (TST_DS, TST_DT)  SELECT TOP 2000 TST_DS , TST_DT FROM TESTE


BACKUP DATABASE TESTE_LOG_SHIPING
TO DISK='D:\LOG_SHIPPING\FULLBACKUP\BACK_TESTE_FULL2.BAK'

BACKUP DATABASE TESTE_LOG_SHIPING
TO DISK='D:\LOG_SHIPPING\DIFFBACKUP\BACK_TESTE_DIFF.BAK'
WITH DIFFERENTIAL

BACKUP LOG TESTE_LOG_SHIPING
TO DISK='D:\LOG_SHIPPING\LogBackUp\BACK_TESTE_LOG.TRN'


ALTER DATABASE TESTE_LOG_SHIPPING_DEST SET SINGLE_USER WITH ROLLBACK
IMMEDIATE
GO
RESTORE DATABASE TESTE_LOG_SHIPPING_TARGE WITH STANDBY
GO
ALTER DATABASE TESTE_LOG_SHIPPING_DEST SET MULTI_USER
GO
