
DECLARE @MyCursor CURSOR

EXEC ADM_ACHA_FILHOS @ADM_ACHA_FILHOS = @MyCursor OUTPUT

PRINT @@FETCH_STATUS

WHILE (@@FETCH_STATUS = 0)
BEGIN
    PRINT 'XXX'
    INSERT INTO ADM_TABELAS (TAB_NM, TAB_NIVEL) VALUES ('SSSSS', 1)
    FETCH NEXT FROM @MyCursor
END

CLOSE @MyCursor
DEALLOCATE @MyCursor
GO
