IF EXISTS (SELECT name FROM sysobjects     
      WHERE name = 'ADM_ACHA_FILHOS' and type = 'P')
DROP PROCEDURE ADM_ACHA_FILHOS
GO
CREATE PROCEDURE ADM_ACHA_FILHOS @ADM_ACHA_FILHOS CURSOR VARYING OUTPUT
AS
SET @ADM_ACHA_FILHOS = CURSOR
FORWARD_ONLY STATIC FOR

SELECT sysobjects.NAME AS TAB_FILHA
FROM sysforeignkeys
 JOIN sysobjects
   on  sysforeignkeys.FKEYID = sysobjects.ID
WHERE  sysforeignkeys.RKEYID IN (SELECT ID FROM sysobjects WHERE NAME LIKE 'PACIENTE')

OPEN @ADM_ACHA_FILHOS
GO
